@inline value_type(::AbstractSampler{Ts}) where {Ts} = Ts
@inline weight_type(::AbstractSampler{Ts, Tw}) where {Ts, Tw} = Tw

# convenience function for allocating samples
@inline function allocate_samples(backend, ::AbstractSampler{Ts, Tw}, batch_size) where {Ts, Tw}
    return allocate_samples(backend, Ts, Tw, batch_size)
end

### User-facing sampler API


# TODO:
# - update docs
# - add unit testsj
"""
rand_single([rng::AbstractRNG = default_rng()], Sampler::AbstractSampler)::Sample

Draw a single `Sample` from `sampler` using the global default RNG.

!!! warning

    This only works on CPU.

"""
function rand_single(rng::AbstractRNG, sampler::AbstractSampler)
    return _rand_single(rng, sampler)
end
# TODO: find out how rand() finds the correct default_rng if called in a KA kernel
#rand_single(sampler::AbstractSampler) = rand_single(Random.default_rng(), sampler)


# TODO:
# - write unit tests checking different versions of this
"""
    Random.rand!(
[rng::AbstractRNG = default_rng()],
        sampler::AbstractProposalDistribution,
        samples::AbstractVector,
        backend = get_backend(samples.value)
    ) -> Nothing

Fill `samples` with samplers generated by `sampler`.

The backend is inferred from the array type of `samples` by default,
but can be overridden via the `backend` keyword.

"""
function Random.rand!(
        rng::AbstractRNG,
        sampler::AbstractSampler{Ts, Tw},
        samples::SampleVector{Ts, Tw},
        backend::KernelAbstractions.Backend
    ) where {Ts, Tw}

    _rand!(rng, sampler, samples, backend)
    return nothing
end

@inline function Random.rand!(
        sampler::AbstractSampler{Ts, Tw},
        samples::SampleVector{Ts, Tw},
        backend::KernelAbstractions.Backend
    ) where {Ts, Tw}
    rand!(default_rng(typeof(samples.value)), sampler, samples; backend)
    return nothing
end

@inline function Random.rand!(
        rng::AbstractRNG,
        sampler::AbstractSampler{Ts, Tw},
        samples::SampleVector{Ts, Tw},
    ) where {Ts, Tw}
    rand!(rng, sampler, samples, get_backend(samples.value))
    return nothing
end

@inline function Random.rand!(
        sampler::AbstractSampler{Ts, Tw},
        samples::SampleVector{Ts, Tw},
    ) where {Ts, Tw}
    rand!(default_rng(typeof(samples.value)), sampler, samples, get_backend(samples.value))
    return nothing
end
