@inline value_type(::AbstractSampler{Ts}) where {Ts} = Ts
@inline weight_type(::AbstractSampler{Ts, Tw}) where {Ts, Tw} = Tw

# convenience function for allocating samples
@inline function allocate_samples(backend, ::AbstractSampler{Ts, Tw}, batch_size) where {Ts, Tw}
    return allocate_samples(backend, Ts, Tw, batch_size)
end

# additional layer for multiple dispatch, especially for different backends
function _rand!(
        rng::Random.AbstractRNG,
        sampler::AbstractSampler,
        samples::AbstractVector,
        backend::KernelAbstractions.Backend
    )
    _rand_on_device!(rng, sampler, samples, backend)
    return nothing
end

# CPU version: fallback on _rand_single
function _rand_on_device!(
        rng::Random.AbstractRNG,
        sampler::AbstractSampler,
        samples::AbstractVector,
        ::KernelAbstractions.CPU,
    )
    @inbounds for i in eachindex(samples)
        single_sample = _rand_single(rng, sampler)
        samples.value[i], samples.weight[i] = single_sample.value, single_sample.weight
    end
    return nothing
end


### User-facing sampler API

"""
    rand_single(Sampler::AbstractSampler)::Sample

Draw a single `Sample` from `sampler` using the global default RNG.

!!! warning

    This only works on CPU.

"""
function rand_single(rng::AbstractRNG, sampler::AbstractSampler)
    return _rand_single(rng, proposal)
end
rand_single(sampler::AbstractSampler) = rand_single(Random.default_rng(), sampler)


# TODO:
# - add input checks via more specialized types
"""
    Random.rand!(
        rng::AbstractRNG,
        sampler::AbstractProposalDistribution,
        samples::AbstractVector,
        backend = get_backend(samples.value)
    ) -> Nothing

Fill `samples` with samplers generated by `sampler`.

The backend is inferred from the array type of `samples` by default,
but can be overridden via the `backend` keyword.

"""
function Random.rand!(
        rng::AbstractRNG,
        sampler::AbstractSampler{Ts, Tw},
        samples::SampleVector{Ts, Tw};
        backend = get_backend(samples.value),
    ) where {Ts, Tw}

    _rand!(rng, sampler, samples, backend)
    return nothing
end


"""
    Random.rand!(
        sampler::AbstractSampler,
        samples::AbstractVector,
        rng = default_rng(typeof(samples.value)),
        backend = get_backend(samples.value)
    ) -> Nothing

Convenience wrapper that infers both the RNG and backend from the destination arrays.
"""
function Random.rand!(
        sampler::AbstractSampler{Ts, Tw},
        samples::SampleVector{Ts, Tw},
        rng = default_rng(typeof(samples.value)),
        backend = get_backend(samples.value),
    ) where {Ts, Tw}
    rand!(rng, sampler, samples; backend)
    return nothing

end
