### RNG strategies

abstract type AbstractRNGStrategy end
struct HostSide <: AbstractRNGStrategy end
struct DeviceSide <: AbstractRNGStrategy end

"""
    _rng_strategy(::AbstractRNG)::AbstractRNGStrategy

"""
function _rng_strategy end

#_rng_strategy(::AbstractRNG) = HostSide()
_rng_strategy(::Xoshiro) = HostSide()
_rng_strategy(::MersenneTwister) = HostSide()
_rng_strategy(::GPUArrays.RNG) = HostSide()

### backend specific rand functions
# these functions can be overwritten for different backends
function _rand_backend!(
        rng::R,
        ::HostSide,
        sampler::AbstractSampler{Ts, Tw},
        backend::KernelAbstractions.Backend,
        buf::AbstractSampleBuffer,
    ) where {Ts, Tw, R <: Random.AbstractRNG}

    _rand_from_host!(rng, sampler, backend, buf)

    return nothing
end

function _rand_backend!(
        rng::R,
        ::DeviceSide,
        sampler::AbstractSampler,
        backend::KernelAbstractions.Backend,
        buf::AbstractSampleBuffer
    ) where {R <: AbstractRNG}

    _rand_from_device!(rng, sampler, backend, buf)

    return nothing
end


### internal rand function
# can be overwritten for specific combinations of all inputs (especially combinations of
# rng and sampler)
@inline function _rand!(
        rng::Random.AbstractRNG,
        sampler::AbstractSampler,
        backend::KernelAbstractions.Backend,
        buf::AbstractSampleBuffer
    )
    _rand_backend!(rng, _rng_strategy(rng), sampler, backend, buf)
    return nothing
end
#=
# CPU version: needs _rand_single to be implemented
function _rand_backend!(
        rng::Random.AbstractRNG,
        sampler::AbstractSampler,
        ::KernelAbstractions.CPU,
    buf::AbstractSampleBuffer
    )
    @inbounds for i in 1:length(buf)
        sample = _rand_single(rng, sampler)
        setsample!(buf, sample, idx)
    end
    return nothing
end
=#

### generic implementation which falls back to _rand_single
# NOTE: only works for device side rng and if _rand_single is implemented

@kernel function _rand_gpu_kernel(rng, sampler::AbstractSampler, buf::AbstractSampleBuffer)
    idx = @index(Global, Linear)
    sample = _rand_single(rng, sampler)
    setsample!(buf, sample, idx)
end

function _rand_from_device!(
        rng::AbstractRNG,
        sampler::AbstractSampler,
        backend::KernelAbstractions.Backend,
        buf::AbstractSampleBuffer,
    )
    _rand_gpu_kernel(backend, 32)(
        rng, samples, sampler;
        ndrange = size(samples)
    )
    return nothing
end


### User-facing sampler API

"""
rand_single([rng::AbstractRNG = default_rng()], Sampler::AbstractSampler)::Sample

Draw a single `Sample` from `sampler` using the global default RNG.

!!! warning

    This only works on CPU.

"""
@inline function rand_single(rng::AbstractRNG, sampler::AbstractSampler)
    return _rand_single(rng, sampler)
end

"""
    Random.rand!(
[rng::AbstractRNG = default_rng()],
        sampler::AbstractProposalDistribution,
        samples::AbstractVector,
        backend = get_backend(samples.value)
    ) -> Nothing

Fill `samples` with samplers generated by `sampler`.

The backend is inferred from the array type of `samples` by default,
but can be overridden via the `backend` keyword.

"""
@inline function Random.rand!(
        rng::AbstractRNG,
        sampler::AbstractSampler{Ts, Tw},
        backend::KernelAbstractions.Backend,
        buf::AbstractSampleBuffer
    ) where {Ts, Tw}

    _rand!(rng, sampler, backend, buf)
    return nothing
end

@inline function Random.rand!(
        rng::AbstractRNG,
        sampler::AbstractSampler{Ts, Tw},
        buf::AbstractSampleBuffer
    ) where {Ts, Tw}
    _rand!(rng, sampler, get_backend(buf), buf)
    return nothing
end
