### User-facing proposal API

"""
    propose_single(proposal::AbstractProposalDistribution) -> (sample, weight)

Draw a single `(sample, weight)` pair from `proposal` using the global default RNG.

!!! warning

    This only works on CPU.

"""
function propose_single(proposal::AbstractProposalDistribution)
    return _propose_single(Random.default_rng(), proposal)
end


"""
    propose!(
        rng::AbstractRNG,
        proposal::AbstractProposalDistribution,
        samples::AbstractVector,
        weights::AbstractVector;
        backend = get_backend(samples)
    ) -> Nothing

Fill `samples` and `weights` with proposals generated by `proposal`.

The backend is inferred from the array type of `samples` by default,
but can be overridden via the `backend` keyword.

Throws an `ArgumentError` if `samples` and `weights` have mismatched lengths.
"""
function propose!(
        rng::AbstractRNG,
        proposal::AbstractProposalDistribution{Ts, Tw},
        samples::AbstractVector{Ts},
        weights::AbstractVector{Tw};
        backend = get_backend(samples),
    ) where {Ts, Tw}

    length(samples) == length(weights) || throw(
        ArgumentError(
            "sample and weight arrays must have the same length",
        )
    )

    _propose!(rng, proposal, samples, weights, backend)
    return nothing
end


"""
    propose!(
        proposal::AbstractProposalDistribution,
        samples::AbstractVector,
        weights::AbstractVector;
        rng = default_rng(typeof(samples)),
        backend = get_backend(samples)
    ) -> Nothing

Convenience wrapper that infers both the RNG and backend from the destination arrays.
"""
function propose!(
        proposal::AbstractProposalDistribution{Ts, Tw},
        samples::SV,
        weights::AbstractVector{Tw};
        rng = default_rng(SV),
        backend = get_backend(samples),
    ) where {Ts, Tw, SV <: AbstractVector{Ts}}
    return propose!(rng, proposal, samples, weights; backend)
end
