# variate form, where arguments are SVectors of scalars representing the coordinates
# NOTE: for univariate proposals, use Distributions.Univariate
abstract type CoordinateVariate <: Distributions.VariateForm end

const ProposalVariateForm = Union{Distributions.Univariate, CoordinateVariate}


abstract type AbstractProposalDistribution{Ts, Tw, F <: ProposalVariateForm} end
Base.broadcastable(d::AbstractProposalDistribution) = Ref(d)
sample_type(::AbstractProposalDistribution{Ts}) where {Ts} = Ts
weight_type(::AbstractProposalDistribution{Ts, Tw}) where {Ts, Tw} = Tw
variate_form(::AbstractProposalDistribution{Ts, Tw, F}) where {Ts, Tw, F} = F

"""

    degrees_of_freedom(proposal::AbstractProposalDistribution)::Int

Interface function: return the number of coordinates generated by the proposal.
"""
function degrees_of_freedom end

"""

    _propose_single(::AbstractRNG,::AbstractProposalDistribution)

Interface function for proposal distributions. Return single proposal sample and weight, stored in a tuple.
"""
function _propose_single end

# generic GPU version
"""

    _propose!(rng::GPUArrays.RNG,
        proposal::AbstractProposalDistribution,
        sample_dest::AbstractVector,
        weight_dest::AbstractVector,
        backend::KernelAbstractions.
    )

Interface function for proposal distributions. Usually only implemented for GPU backends. For CPU, one can implement `_propose_single` if available.
"""
function _propose! end

# generic fallback
function _propose!(
        rng::AbstractRNG,
        proposal::AbstractProposalDistribution,
        sample_dest::AbstractVector,
        weight_dest::AbstractVector,
        backend::KernelAbstractions.Backend
    )

    return _propose_on_device!(rng, proposal, sample_dest, weight_dest, backend)

end

function _propose_on_device!(
        rng::AbstractRNG,
        proposal::AbstractProposalDistribution,
        sample_dest::AbstractVector,
        weight_dest::AbstractVector,
        backend::KernelAbstractions.CPU
    )

    @inbounds for i in eachindex(sample_dest)
        sample, weight = _propose_single(rng, proposal)
        sample_dest[i] = sample
        weight_dest[i] = weight
    end

    return nothing
end

### Specializations

const AbstractUnivariateProposal{T} = AbstractProposalDistribution{T, T, Distributions.Univariate}
degrees_of_freedom(::AbstractUnivariateProposal) = 1

const AbstractCoordinateProposal{Ts, Tw} = AbstractProposalDistribution{Ts, Tw, CoordinateVariate}

# based on _rand! + _transform
abstract type AbstractTransformProposal{Ts, Tw} <: AbstractCoordinateProposal{Ts, Tw} end

"""

    _transform(
        proposal::AbstractTransformProposal{T},
        unit_rnd_coord::T
    ) where T

Interface function for local transformations of unit random coordinates. Returns transformed sample and proposal weight as a tuple.
"""
function _transform end

# cpu only
function _propose_single(rng::AbstractRNG, proposal::AbstractTransformProposal{Ts}) where {Ts}
    return _transform(proposal, rand(rng, Ts))
end

@kernel function _propose_gpu_kernel(s, w, proposal::AbstractTransformProposal, randstate)
    idx = @index(Global, Linear)

    sample, weight = _gpu_propose(proposal, ((idx - 1) % length(randstate) + 1), randstate)
    @inbounds s[idx] = sample
    @inbounds w[idx] = weight
end

function _propose_on_device!(
        rng::GPUArrays.RNG,
        proposal::AbstractTransformProposal,
        sample_dest::AbstractVector,
        weight_dest::AbstractVector,
        backend::KernelAbstractions.GPU
    )

    # TODO: remove this if the alternative works
    #=
    @kernel function gpu_propose!(s,w, randstate)
        idx = @index(Global, Linear)

        sample, weight = _gpu_propose(TT, proposal, ((idx - 1) % length(randstate) + 1), randstate)
        @inbounds s[idx] = sample
        @inbounds w[idx] = weight
    end
    gpu_propose!(backend, 32)(sample_dest, weight_dest, rng.state; ndrange = size(sample_dest))
    =#

    return _propose_gpu_kernel(backend, 32)(sample_dest, weight_dest, proposal, rng.state; ndrange = size(sample_dest))
end

# thread-local gpu version
function _gpu_propose(
        u::AbstractTransformProposal{TT},
        threadid,
        randstate::AbstractVector{NTuple{4, UInt32}},
    ) where {N, T, TT <: SVector{N, T}}
    return _transform(u, gpu_rand(TT, threadid, randstate))
end
