# variate form, where arguments are SVectors of scalars representing the coordinates
# NOTE: for univariate proposals, use Distributions.Univariate
abstract type CoordinateVariate <: Distributions.VariateForm end

const ProposalVariateForm = Union{Distributions.Uniform,CoordinateVariate}

"""

    AbstractProposal{T}

Proposal distribution super type with element type `T`.
Interface functions, which must be implemented

```
_rand!(rng,dist,dest)
```

which generates random numbers and stores them in `dest`. Possible `dest` types are

- `Vector`
- `CuVector`
- `ROCArray`
- `OneArray`
- `MtlArray`

Depending on `rng`, the random numbers are generated directly on device, or they are generated on
cpu and copyied to the device.

!!! note

    Even if this is a subtype of `Sampleable{Univariate}`, we distinguish **univariate**
    proposal, which have real element types `T<:Real`, and **multivariate** targets, if the
    element type is a `NTuple`. In the terminology of `Distributions.jl`, both are
    technically considered *univariate*. However, we differentiate them because our current data
    layout represents coordinates as a single `NTuple` and phase space points as collections of
    such `NTuples`.

"""
abstract type AbstractProposal{T,F<:AbstractProposalVariate} end
Base.broadcastable(d::AbstractProposal) = Ref(d)
Base.eltype(::AbstractProposal{T}) where {T} = T
variate_form(::AbstractProposal{T,F}) where {T,F} = F

"""

    _rand!(rng::AbstractRNG, proposal::AbstractProposal{T}, dest::AbstractVector{T}) where T

Interface function for proposal generation. The element type `T` is purposely not restricted to numbers, but should at least support `T<:NTuple{N,<:Real}`.
"""
function _rand! end

"""

    degree_of_freedom(proposal::AbstractProposal)

Interface function: retrun number of coordinates generated by the proposal.
"""
function degree_of_freedom end
