# variate form, where arguments are SVectors of scalars representing the coordinates
# NOTE: for univariate proposals, use Distributions.Univariate
abstract type CoordinateVariate <: Distributions.VariateForm end

const ProposalVariateForm = Union{Distributions.Univariate,CoordinateVariate}

"""

    AbstractProposal{T}

Proposal distribution super type with element type `T`.
Interface functions, which must be implemented

```
degree_of_freedom(dist)
_rand!(rng,dist,dest)
```

which generates random numbers and stores them in `dest`. Possible `dest` types are

- `Vector`
- `CuVector`
- `ROCArray`
- `OneArray`
- `MtlArray`

Depending on `rng`, the random numbers are generated directly on device, or they are generated on
cpu and copyied to the device.

!!! note

    Even if this is a subtype of `Sampleable{Univariate}`, we distinguish **univariate**
    proposal, which have real element types `T<:Real`, and **multivariate** targets, if the
    element type is a `NTuple`. In the terminology of `Distributions.jl`, both are
    technically considered *univariate*. However, we differentiate them because our current data
    layout represents coordinates as a single `NTuple` and phase space points as collections of
    such `NTuples`.

"""
abstract type AbstractProposal{T,F<:ProposalVariateForm} end
Base.broadcastable(d::AbstractProposal) = Ref(d)
Base.eltype(::AbstractProposal{T}) where {T} = T
variate_form(::AbstractProposal{T,F}) where {T,F} = F


"""

    _rand!(rng::AbstractRNG, proposal::AbstractProposal{T}, dest::AbstractVector{T}) where T

Interface function for proposal generation. The element type `T` is purposely not restricted to numbers, but should at least support `T<:NTuple{N,<:Real}`.
"""
function _rand! end

"""

    degree_of_freedom(proposal::AbstractProposal)

Interface function: retrun number of coordinates generated by the proposal.
"""
function degree_of_freedom end

# Specializations
const AbstractUnivariateProposal{T} = AbstractProposal{T,Distributions.Univariate}
degree_of_freedom(::AbstractUnivariateProposal) = 1

const AbstractCoordinateProposal{T} = AbstractProposal{T,CoordinateVariate}

# global transformation based proposal
abstract type AbstractGlobalTransformProposal{T} <: AbstractCoordinateProposal{T} end

"""

    _global_transform!(proposal::AbstractTransformationBasedProposal{T},unit_rnd_coords::AbstractVector{T}) where T


Interface function: transform `unit_rnd_coords` into coordinate SVectors according to the given `proposal`.
"""
function _global_transform! end

# TODO:
# - check if rand and transform are fused on GPU
# - if not: benchmark against local transform
function _rand!(
    rng::AbstractRNG,
    proposal::AbstractGlobalTransformProposal{TT},
    dest::AbstractVector{TT},
) where {T,N,TT<:SVector{N,T}}
    _rand!(rng, dest)
    _global_transform!(proposal, dest)

    return dest
end

# local transformation based proposal
abstract type AbstractLocalTransformProposal{T} <: AbstractCoordinateProposal{T} end

"""

    _local_transform(proposal::AbstractLocalTransformProposal{T}, unit_rnd_coord::T) where T

Interface function: return transformed coordinates according to `proposal`.
"""
function _local_transform end

# cpu version
function _rand!(
    rng::AbstractRNG,
    proposal::AbstractLocalTransformProposal{TT},
    dest::AbstractVector{TT},
) where {T,N,TT<:SVector{N,T}}
    isempty(dest) && return dest

    for i in eachindex(dest)
        dest[i] = _local_transform(proposal, rand(rng, TT))
    end
    return dest
end

#gpu version
function gpu_rand(
    ::Type{TT},
    u::AbstractLocalTransformProposal{TT},
    threadid,
    randstate::AbstractVector{NTuple{4,UInt32}},
) where {N,T,TT<:SVector{N,T}}
    return _local_transform(u, gpu_rand(TT, threadid, randstate))
end

function _rand!(
    rng::GPUArrays.RNG,
    proposal::AbstractLocalTransformProposal{TT},
    A::GPUArrays.AnyGPUArray{TT},
) where {N,T,TT<:SVector{N,T}}
    isempty(A) && return A
    @kernel function rand!(a, randstate)
        idx = @index(Global, Linear)
        @inbounds a[idx] =
            gpu_rand(TT, proposal, ((idx - 1) % length(randstate) + 1), randstate)
    end
    rand!(get_backend(A))(A, rng.state; ndrange = size(A))
    return A
end
